export const SUBJECT_UNITS: Record<string, string> = {
  "Movement Competency Training": "2.0",
  "Exercise-based Fitness Activities": "2.0",
  "Menu of Dance, Sports, Martial Arts, Group Exercise, Outdoor and Adventure Activities":
    "2.0",
  "CWTS/LTS/ROTC": "3.0",
  "Understanding the Self": "3.0",
  "Readings in Philippine History": "3.0",
  "The Contemporary World": "3.0",
  "Mathematics in the Modern World": "3.0",
  "Purposive Communication": "3.0",
  "Art Appreciation": "3.0",
  "Science, Technology and Society": "3.0",
  Ethics: "3.0",
  "Environmental Science": "3.0",
  "The Entrepreneurial Mind": "3.0",
  "Great Books": "3.0",
  "Introduction to Computing": "3.0",
  "Computer Programming 1": "3.0",
  "Computer Programming 2": "3.0",
  "Data Structure and Algorithm": "3.0",
  "Object Oriented Programming": "3.0",
  "Discrete Structures 1": "3.0",
  "Discrete Structures 2": "3.0",
  "Computer Architecture and Organization": "3.0",
  "Operating Systems": "3.0",
  "Networks and Communication": "3.0",
  "Automata Theory and Formal Languages": "3.0",
  "Programming Languages": "3.0",
  "Information Management": "3.0",
  "Software Engineering 1": "3.0",
  "Software Engineering 2": "3.0",
  "Human Computer Interaction": "3.0",
  "Information Assurance and Security": "3.0",
  "Design and Analysis of Algorithm": "3.0",
  "Applications Development and Emerging Technologies": "3.0",
  "Special Topics in Computing": "3.0",
  "Computer Security and Cryptography": "3.0",
  "Digital Systems Design": "3.0",
  "Thesis 1": "3.0",
  "Physics for Computing": "3.0",
  "Mathematical Analysis 1": "5.0",
  "Mathematical Analysis 2": "5.0",
  "Linear Algebra": "3.0",
  "Differential Equations": "3.0",
  "Numerical Analysis": "3.0",
  "CS Elec 1": "3.0",
  "CS Elec 3": "3.0",
  "Practicum (240 Hours)": "3.0",
};
